/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "name", input: never, result: string } | 
        { key: "todos", input: never, result: Todo[] } | 
        { key: "users", input: User, result: User } | 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "create_todos", input: Todo, result: null },
    subscriptions: never
};

export type Todo = { title: string }

export type User = { name: string; email: string }
