/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "name", input: never, result: string } | 
        { key: "users", input: User, result: User } | 
        { key: "version", input: never, result: string },
    mutations: never,
    subscriptions: never
};

export type User = { name: string; email: string }
